#!/bin/bash

WORKDIR="${WORKDIR:-$HOME/ICA_3RF3}"

PDB_ID="${PDB_ID:-3RF3}"
PDB_FILE="${PDB_FILE:-${PDB_ID}.pdb}"
INPUT_PDB="${INPUT_PDB:-$PDB_FILE}"
DOWNLOAD_PDB="${DOWNLOAD_PDB:-1}"

FORCE_FIELD="${FORCE_FIELD:-amber99sb-ildn}"
WATER_MODEL="${WATER_MODEL:-tip3p}"
BOX_DISTANCE_NM="${BOX_DISTANCE_NM:-1.0}"
ION_CONCENTRATION_M="${ION_CONCENTRATION_M:-0.15}"

TEMPERATURES=(${TEMPERATURES:-280 300 320})
PRODUCTION_THREADS="${PRODUCTION_THREADS:-16}"
MDRUN_NB="${MDRUN_NB:-gpu}"

ANALYSIS_START_NS="${ANALYSIS_START_NS:-40}"
FINAL_FRAME_PS="${FINAL_FRAME_PS:-50000}"
DSSP_TAIL_LINES="${DSSP_TAIL_LINES:-1000}"

# These ranges are based on the original project topology and should be checked
# again if the input structure or protonation state changes.
CHAIN_A_RANGE="${CHAIN_A_RANGE:-1-4095}"
CHAIN_B_RANGE="${CHAIN_B_RANGE:-4096-4477}"
CHAIN_A_NAME="${CHAIN_A_NAME:-chain_A}"
CHAIN_B_NAME="${CHAIN_B_NAME:-chain_B}"

ARTIFACTS_DIR="${ARTIFACTS_DIR:-$WORKDIR/analysis_artifacts}"
SUMMARY_DIR="${SUMMARY_DIR:-$ARTIFACTS_DIR/summaries}"
FINAL_STRUCTURES_DIR="${FINAL_STRUCTURES_DIR:-$ARTIFACTS_DIR/final_structures}"
